name: Run Automation
on:
  schedule:
    - cron: '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: npm ci

      - name: Run automated Linear workflow
        run: npm run automate
        env:
          API_KEY: ${{ secrets.API_KEY }}